export enum Cursos {
    ADMINISTRACAO = 'Administração',
    BIOMEDICINA = 'Biomedicina',
    CIENCIAS_CONTABEIS = 'Ciências Contábeis',
    CIENCIA_DA_COMPUTACAO = 'Ciência da Computação',
    DIREITO = 'Direito',
    EDUCACAO_FISICA_BACHARELADO = 'Educação Física (Bacharelado)',
    EDUCACAO_FISICA_LICENCIATURA = 'Educação Física (Licenciatura)',
    ENFERMAGEM = 'Enfermagem',
    ESTETICA_E_COSMETICA_PRESENCIAL = 'Eestetica e Cosmetica (Presencial)',
    ESTETICA_E_COSMETICA_SEMIPRESENCIAL = 'Eestetica e Cosmetica (Semipresencial)',
    FARMACIA = 'Farmácia',
    FISIOTERAPIA = 'Fisioterapia',
    FONOAUDIOLOGIA = 'Fonoaudilogia',
    MEDICINA = 'Medicina',
    NUTRICAO = 'Nutrição',
    ODONTOLOGIA_INTEGRAL = 'Odontologia (Integral)',
    ODONTOLOGIA_NOTURNO = 'Odontologia (Noturno)',
    PEDAGOGIA = 'Pedagogia',
    PSICOLOGIA = 'Psicologia',
    TERAPIA_OCUPACIONAL = 'Terapia Ocupacional',
}