services: #(onde ficam as máquinas)
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: pi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: grupo_4
      POSTGRES_PASSWORD: grupo_41235
      POSTGRES_DB: projeto_integrador
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    # Serviço do Backend (Adicionado aqui)
  backend:
    build:
      context: . # O ponto significa "esta mesma pasta" onde o compose está
      dockerfile: Dockerfile # Caminho para a pasta onde está o seu Dockerfile
    container_name: pi_backend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Variáveis que o seu knexfile.ts e app.ts vão usar
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=grupo_4
      - DATABASE_PASSWORD=grupo_41235
      - DATABASE_NAME=projeto_integrador
      - NODE_ENV=development
      # Se usar DATABASE_URL: postgres://grupo_4:grupo_41235@db:5432/projeto_integrador
    depends_on:
      - db # Faz o backend esperar o container do banco subir

volumes: #(onde ficam os discos rígidos virtuais)
  pgdata: # Garante que os dados do banco não sumam ao desligar o Docker


#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Atenção ao DATABASE_URL

# Note que na sua DATABASE_URL, o endereço é @db:5432.
# Isso está correto! Dentro da rede do Docker, a sua API não enxerga o banco como localhost,
# mas sim pelo nome do serviço que definimos lá em cima (db).

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Por que o volumes é importante?

# Sem o bloco volumes no final, toda vez que você desligasse o Docker,
# todos os dados que você cadastrou no seu Projeto Integrador (as avaliações, usuários, etc.)
#  seriam apagados. O volume cria uma pasta "persistente" no seu HD que o Docker usa para salvar o estado do banco.